# docker run -it --rm --memory=256m --memory-swap=0 --cpu-shares=80 --rm --name backend1 -p 9000:9000 -v `pwd`/:/var/www/unsee/:ro backend
backend:
  build: .
  volumes:
    - .:/var/www/unsee/
  ports:
    - 9000:9000
  net: host
